### ISSUE TITLE
the algorithms in some of the modules

### ISSUE THREAD

**Issue by bezoldbrucke** [cruxopen/openISP#2]
Hi,

I found the openISP very interesting. While I am able to understand part of the code, I still get confused about some of the algorithms, and why it is done in one way or another. For example, the edge enhancement part and the chroma suppression part after demosaic. Can you share a little bit more about the algorithm so that I can better understand your code? Or where i can find the algorithms online.

Thanks a lot,
jun

**Comment by cruxopen** [comment]
> Hi,
> 
> I found the openISP very interesting. While I am able to understand part of the code, I still get confused about some of the algorithms, and why it is done in one way or another. For example, the edge enhancement part and the chroma suppression part after demosaic. Can you share a little bit more about the algorithm so that I can better understand your code? Or where i can find the algorithms online.
> 
> Thanks a lot,
> jun

I was busy on other things recently. I've prepared some docs for openISP, hopefully will upload it soon.
