### ISSUE TITLE
dpc.py line 28, 29

### ISSUE THREAD

**Issue by spencersweet0530** [cruxopen/openISP#20]
code read
p0 = img_pad[y + 2, x + 2]
p1 = img_pad[y, x]

peper read
p0 in [y, x]
p1 in [y + 2, x + 2]

Excuse me, which one is right ??

**Comment by Kuo-TingKai** [comment]
Pixel array in code is showed above:

p1  p2  p3          
p4  p0  p5
p6  p7  p8

it makes sense for calculating follow-up gradients of pixel values (horizontal,vertical,left/right diagonal).

**Comment by spencersweet0530** [comment]
> 代碼中的像素數組如上所示：
> 
> p1 p2 p3 p4 p0 p5 p6 p7 p8
> 
> 這對於計算像素值（水平、垂直、左/右對角線）的後續梯度很有意義。

thanks bro
