### ISSUE TITLE
a bug in hsc.py

### ISSUE THREAD

**Issue by bezoldbrucke** [cruxopen/openISP#3]
https://github.com/cruxopen/openISP/blob/14034f37d4dae0c061c425425d33eb9f1a2e6265/model/hsc.py#L35

                hsc_img[y,x,0] = (self.img[y,x,0] - 128) * lut_cos[self.hue] + (self.img[y,x,1] - 128) * lut_sin[self.hue] + 128
                hsc_img[y,x,1] = (self.img[y,x,1] - 128) * lut_cos[self.hue] - (self.img[y,x,0] - 128) * lut_sin[self.hue] + 128
                hsc_img[y,x,0] = self.saturation * (self.img[y,x,0] - 128) / 256 + 128
                hsc_img[y,x,1] = self.saturation * (self.img[y,x,1] - 128) / 256 + 128

The hsc_img[y,x,0] and hsc_img[y,x,1] in the first two lines are not used. is it correct?

**Comment by Lz8240** [comment]
I suppose the hue control and the saturation control can be seprated.  They are adjusted according to demand. Since the causal relationship is not that strong, the author design the code like this. The other part "bcc.py" is in the same situation.

**Comment by cruxopen** [comment]
> https://github.com/cruxopen/openISP/blob/14034f37d4dae0c061c425425d33eb9f1a2e6265/model/hsc.py#L35
> 
> ```
>             hsc_img[y,x,0] = (self.img[y,x,0] - 128) * lut_cos[self.hue] + (self.img[y,x,1] - 128) * lut_sin[self.hue] + 128
>             hsc_img[y,x,1] = (self.img[y,x,1] - 128) * lut_cos[self.hue] - (self.img[y,x,0] - 128) * lut_sin[self.hue] + 128
>             hsc_img[y,x,0] = self.saturation * (self.img[y,x,0] - 128) / 256 + 128
>             hsc_img[y,x,1] = self.saturation * (self.img[y,x,1] - 128) / 256 + 128
> ```
> 
> The hsc_img[y,x,0] and hsc_img[y,x,1] in the first two lines are not used. is it correct?

I made a mistake. Bugs fixed.
