### ISSUE TITLE
[blc.py] maybe a bug in execute function in blc.py

### ISSUE THREAD

**Issue by duanyayong** [cruxopen/openISP#7]
**"elif bayer_pattern == 'bggr'" ====>   "elif self.bayer_patter == 'bggr'"
"elif bayer_pattern == 'gbrg'" ====>   "elif self.bayer_patter == 'gbrg'"
"elif bayer_pattern == 'grbg'" ====>   "elif self.bayer_patter == 'grbg'"**

Hi Crux,

According the context, I think you maybe want to get the value of "self.bayer_pattern" to decide which way to do blc rather than "bayer_pattern".

Thanks!
Yayong

**Comment by cruxopen** [comment]
Noted with thanks. Fixed in latest commit.
