### ISSUE TITLE
what is chroma noise filtering

### ISSUE THREAD

**Issue by liwenjian12** [cruxopen/openISP#8]
hello，I‘m wondering what is chroma noise filtering come from , why do we need this one ,is there any paper to cover it,  appreciate your feedback

**Comment by cruxopen** [comment]
> hello，I‘m wondering what is chroma noise filtering come from , why do we need this one ,is there any paper to cover it, appreciate your feedback

As named, chroma noise filter is to denoise the chroma noise. Many noise types appear on one image, such as static, dynamic etc. Regarding to noise domain, luma and chroma domains have their own noise respectively. It is suggested to denoise on both domains separately. 

You may refer to the patent and search for chroma noise reduction in google.
https://patents.google.com/patent/US20130064448
